<?php
// -------------------------------------------------------------------
// This file was automatically generated by the LangBuilder.php script
// Date of creation: 2010/09/06 09:19:09
// -------------------------------------------------------------------
global $lang;


// Output for class or file: FormularioDeContacto
$lang['en_US']['FormularioDeContacto']['GOOGLEMAPS'] = 'Add your Google Maps info';

// Output for class or file: Page
$lang['en_US']['Page']['CATEGORYHOWMANY'] = 'How many children we will show at the same time?';
$lang['en_US']['Page']['SELECTHOWMANY'] = '= select how many =';
$lang['en_US']['Page']['FILESTAB'] = 'Files';
$lang['en_US']['Page']['LAYOUTTAB'] = 'Layouts';
$lang['en_US']['Page']['SHOWINHEADERMENU'] = 'Show in header henu';
$lang['en_US']['Page']['SHOWINFOOTERMENU'] = 'Show in footer menu';
$lang['en_US']['Page']['SHOWCHILDREN'] = 'Show children?';
$lang['en_US']['Page']['PROMOTEHOME'] = 'Promote to homepage';
$lang['en_US']['Page']['FORHOMEPhoto'] = 'Photo for promoted to home pages';

// Output for class or file: PageHolderLayouts
$lang['en_US']['PageHolderLayouts']['LAYOUTPROPERTIES'] = 'Layout Properties';

// Output for class or file: HomePage
$lang['en_US']['HomePage']['CONTACTDETAILSTAB'] = 'ContactDetails';
$lang['en_US']['HomePage']['CONTACTDETAILSINFO'] = 'this information will appear in the footer of every page';
$lang['en_US']['HomePage']['CONTACTINFO'] = 'ContactInfo';

// Output for class or file: Maintenance
$lang['en_US']['Maintenance']['MAINTENANCE'] = 'Put the site into maintenance mode?';
$lang['en_US']['Maintenance']['MESSAGE'] = 'Site under maintenance';

// Output for class or file: WidgetAreaDecorator
$lang['en_US']['WidgetAreaDecorator']['INTERACTIONCOLUMN'] = 'Interaction Column';

// Output for class or file: AddContent
$lang['en_US']['AddContent']['DELETEEXISTING'] = 'Clear out all existing content?';
$lang['en_US']['AddContent']['PUBLISHALL'] = 'Publish everything after the import?';
$lang['en_US']['AddContent']['BULKIMPORT'] = 'Import pages';
$lang['en_US']['AddContent']['SITEIMPORTED'] = '<p>Thanks! Your site tree has been imported.</p>';

// Output for class or file: NCSimpleTreeDropdownField
$lang['en_US']['NCSimpleTreeDropdownField']['UNTITLED'] = 'Untitled';

// Output for class or file: CMSNavigator
$lang['en_US']['CMSNavigator']['DRAFTSITE'] = 'Draft Site';
$lang['en_US']['CMSNavigator']['PUBLISHEDSITE'] = 'Published Site';
$lang['en_US']['CMSNavigator']['ARCHIVEDSITE'] = 'Archived Site';
$lang['en_US']['CMSNavigator']['ADMINAREA'] = 'Admin Area';
$lang['en_US']['CMSNavigator']['EDITTHISPAGE'] = 'Edit this Page';
$lang['en_US']['CMSNavigator']['VIEWPUBLISHEDSITE'] = 'View Published Site';
$lang['en_US']['CMSNavigator']['VIEWDRAFTSITE'] = 'View Draft Site';
$lang['en_US']['CMSNavigator']['FLUSHCACHE'] = 'Flush cache';
$lang['en_US']['CMSNavigator']['REBUILDSITE'] = 'Rebuild Site';
$lang['en_US']['CMSNavigator']['ADDCONTENTUSINGTXTFILE'] = 'Add Content using txt file';
$lang['en_US']['CMSNavigator']['LOGGEDINAS'] = 'Logged in as ';
$lang['en_US']['CMSNavigator']['LOGOUT'] = 'Logout';
$lang['en_US']['CMSNavigator']['NOTLOGGEDIN'] = 'Not logged in';
$lang['en_US']['CMSNavigator']['LOGIN'] = 'log in';

// Output for class or file: Paginate
$lang['en_US']['Paginate']['PREVIOUS'] = 'Previous';
$lang['en_US']['Paginate']['NEXT'] = 'Next';

// Output for class or file: dospuntoceroCMS
$lang['en_US']['dospuntoceroCMS']['MAINTENANCE'] = 'site under maintenance';
