<?php
// -------------------------------------------------------------------
// This file was automatically generated by the LangBuilder.php script
// Date of creation: 2010/03/13 20:58:27
// -------------------------------------------------------------------
global $lang;


// Output for class or file: Page
$lang['en_US']['Page']['FILESTAB'] = 'Files';
$lang['en_US']['Page']['URLSEGMENT'] = 'Url for this page';
$lang['en_US']['Page']['SHOWINHEADERMENU'] = 'Show in header henu';
$lang['en_US']['Page']['SHOWINFOOTERMENU'] = 'Show in footer menu';
$lang['en_US']['Page']['FEATURE'] = 'Destacar';
$lang['en_US']['Page']['FRASE'] = 'Frase';
$lang['en_US']['Page']['SEARCH'] = 'Search';
                                                 

// Output for class or file: Page_results
$lang['en_US']['Page_results']['RESULTS'] = 'Results for word: ';
$lang['en_US']['Page_results']['READMOREABOUT'] = 'read more about';
$lang['en_US']['Page_results']['READMORE'] = 'read more';
$lang['en_US']['Page_results']['SEARCHEMPTY'] = 'no results';
$lang['en_US']['Page_results']['NEXTPAGE'] = 'next';
$lang['en_US']['Page_results']['PREVPAGE'] = 'previous';

$lang['en_US']['Page']['TRANSLATIONS'] = 'Select Language';
